version: "3"

services:
  movies-app-backend:
    container_name: movies-app-backend
    image: movies-app-backend:latest
    restart: always
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - movies-app-mongo
    links:
      - movies-app-mongo
    environment:
      MONGO_ADDRESS: movies-app-mongo

  movies-app-mongo:
    container_name: movies-app-mongo
    image: library/mongo:4.2.8-bionic
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"